<?php
    define('DURATION_COOKIE_VIEW_SECONDS', 60);
    define('DURATION_COOKIE_VIEW_MINUTES', 30);
    define('DURATION_COOKIE_VIEW_HOURS', 1);
    define('DURATION_COOKIE_VIEW_DAY', 1);
    define('DURATION_COOKIE_VIEW_MONTH', 1);